//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileTransferApp_Mobile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileTransferApp_Mobile.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Files.
        /// </summary>
        internal static string Ac_btnReceive {
            get {
                return ResourceManager.GetString("Ac_btnReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Files.
        /// </summary>
        internal static string Ac_btnSend {
            get {
                return ResourceManager.GetString("Ac_btnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose what to do..
        /// </summary>
        internal static string Ac_InfoMessage {
            get {
                return ResourceManager.GetString("Ac_InfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Done_btnHome {
            get {
                return ResourceManager.GetString("Done_btnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Done_btnOpen {
            get {
                return ResourceManager.GetString("Done_btnOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File transfer is succesful!.
        /// </summary>
        internal static string Done_InfoMessage {
            get {
                return ResourceManager.GetString("Done_InfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string Done_lblFiles {
            get {
                return ResourceManager.GetString("Done_lblFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more.
        /// </summary>
        internal static string File_btnAdd {
            get {
                return ResourceManager.GetString("File_btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm files.
        /// </summary>
        internal static string File_btnConfirm {
            get {
                return ResourceManager.GetString("File_btnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string File_btnOpen {
            get {
                return ResourceManager.GetString("File_btnOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string File_btnRemove {
            get {
                return ResourceManager.GetString("File_btnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review selected files..
        /// </summary>
        internal static string File_InfoMessage {
            get {
                return ResourceManager.GetString("File_InfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of selected files.
        /// </summary>
        internal static string File_SelectedList {
            get {
                return ResourceManager.GetString("File_SelectedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file is selected!.
        /// </summary>
        internal static string Files_Warning_NoFile {
            get {
                return ResourceManager.GetString("Files_Warning_NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for using this application. You can follow and support us for more!.
        /// </summary>
        internal static string Info_InfoMessage {
            get {
                return ResourceManager.GetString("Info_InfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select FIles.
        /// </summary>
        internal static string Main_btnSelect {
            get {
                return ResourceManager.GetString("Main_btnSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plase make sure that your phone and the receiver device are connected to same Wi-Fi!.
        /// </summary>
        internal static string Main_InfoMessage1 {
            get {
                return ResourceManager.GetString("Main_InfoMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the files you want to send. You can select multiple files..
        /// </summary>
        internal static string Main_InfoMessage2 {
            get {
                return ResourceManager.GetString("Main_InfoMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Permission_btnAccept {
            get {
                return ResourceManager.GetString("Permission_btnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Request.
        /// </summary>
        internal static string Permission_InfoMessage {
            get {
                return ResourceManager.GetString("Permission_InfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wants to send you some files : .
        /// </summary>
        internal static string Permission_RequestMessage {
            get {
                return ResourceManager.GetString("Permission_RequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to receive?.
        /// </summary>
        internal static string Permission_RequestMessage2 {
            get {
                return ResourceManager.GetString("Permission_RequestMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        internal static string Permisson_btnDecline {
            get {
                return ResourceManager.GetString("Permisson_btnDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for connection....
        /// </summary>
        internal static string Rec_InfoMessage {
            get {
                return ResourceManager.GetString("Rec_InfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Send_btnRefresh {
            get {
                return ResourceManager.GetString("Send_btnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send_btnSend {
            get {
                return ResourceManager.GetString("Send_btnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available device list :.
        /// </summary>
        internal static string Send_deviceList {
            get {
                return ResourceManager.GetString("Send_deviceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the target device.
        /// </summary>
        internal static string Send_infoMessage {
            get {
                return ResourceManager.GetString("Send_infoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning Network....
        /// </summary>
        internal static string Send_Scanning {
            get {
                return ResourceManager.GetString("Send_Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target IP :.
        /// </summary>
        internal static string Send_TargetIP {
            get {
                return ResourceManager.GetString("Send_TargetIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t go back after sending a request. Sorry....
        /// </summary>
        internal static string Send_Warning_Goback {
            get {
                return ResourceManager.GetString("Send_Warning_Goback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry... Transfer request is rejected by.
        /// </summary>
        internal static string Send_Warning_rejected {
            get {
                return ResourceManager.GetString("Send_Warning_rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Setting_btnSave {
            get {
                return ResourceManager.GetString("Setting_btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name :.
        /// </summary>
        internal static string Setting_DeviceName {
            get {
                return ResourceManager.GetString("Setting_DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language :.
        /// </summary>
        internal static string Setting_Language {
            get {
                return ResourceManager.GetString("Setting_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Parameters....
        /// </summary>
        internal static string Setting_Warning_Saving {
            get {
                return ResourceManager.GetString("Setting_Warning_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is better to change the name of your device so that you can easily recognize it later.
        ///                           This name will be seen when you want to receive files. You can also change the language of this app.
        /// </summary>
        internal static string Settings_fristTimeInfo {
            get {
                return ResourceManager.GetString("Settings_fristTimeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Buggy File Transfer App!.
        /// </summary>
        internal static string Settings_WelcomeMessage {
            get {
                return ResourceManager.GetString("Settings_WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Transfer_btnAbort {
            get {
                return ResourceManager.GetString("Transfer_btnAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to cancel transfer?.
        /// </summary>
        internal static string Transfer_ConfirmAbortMessage {
            get {
                return ResourceManager.GetString("Transfer_ConfirmAbortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Transfer_ConfirmAbortNo {
            get {
                return ResourceManager.GetString("Transfer_ConfirmAbortNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Transfer_ConfirmAbortTitle {
            get {
                return ResourceManager.GetString("Transfer_ConfirmAbortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Transfer_ConfirmAbortYes {
            get {
                return ResourceManager.GetString("Transfer_ConfirmAbortYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name :.
        /// </summary>
        internal static string Transfer_Filename {
            get {
                return ResourceManager.GetString("Transfer_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size :.
        /// </summary>
        internal static string Transfer_FileSize {
            get {
                return ResourceManager.GetString("Transfer_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files are being transferred....
        /// </summary>
        internal static string Transfer_InfoMessage {
            get {
                return ResourceManager.GetString("Transfer_InfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining :.
        /// </summary>
        internal static string Transfer_Remaining {
            get {
                return ResourceManager.GetString("Transfer_Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time :.
        /// </summary>
        internal static string Transfer_Time {
            get {
                return ResourceManager.GetString("Transfer_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer speed :.
        /// </summary>
        internal static string Transfer_TransferSpeed {
            get {
                return ResourceManager.GetString("Transfer_TransferSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t go back while transferring!.
        /// </summary>
        internal static string Transfer_Warning_GoBack {
            get {
                return ResourceManager.GetString("Transfer_Warning_GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Device Name:.
        /// </summary>
        internal static string YourDeviceName {
            get {
                return ResourceManager.GetString("YourDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your IP Address.
        /// </summary>
        internal static string YourIPAddress {
            get {
                return ResourceManager.GetString("YourIPAddress", resourceCulture);
            }
        }
    }
}
